base:
  project: diabetes-prediction-project
  random_state: 20
  target_col: Outcome

data_source:
  original_source: source_data/diabetes.csv

load_data:
  raw_dataset_csv: data/raw/diabetes.csv

split_data:
  train_path: data/processed/train_diabetes.csv
  test_path: data/processed/test_diabetes.csv
  test_size: 0.2

estimators:
  LogisticRegression:
    params:
      # The Elastic-Net mixing parameter, with 0 <= l1_ratio <= 1, is only used if penalty='elasticnet', which is only supported by saga solver
      # Setting l1_ratio=0 is equivalent to using penalty='l2', while setting l1_ratio=1 is equivalent to using penalty='l1'. For 0 < l1_ratio <1, the penalty is a combination of L1 and L2.
      solver: 'saga'
      penalty: 'elasticnet'
      l1_ratio: 0
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib
